version: '3.8'

services:
  # MongoDB as Firestore alternative
  mongodb:
    image: mongo:7.0
    container_name: travel-planner-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: travel_planner
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - travel-network

  # Optional: MongoDB Admin UI
  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: travel-planner-mongo-ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - travel-network

volumes:
  mongodb_data:

networks:
  travel-network:
    driver: bridge 